# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'VoiceAid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VoiceAid
pod 'GoogleMaps'
  target 'VoiceAid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  end

  target 'VoiceAidTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
